version: '3'
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
        - NEO4J_AUTH=none
        - NEO4J_dbms_memory_pagecache_size=1G
        - NEO4J_dbms.memory.heap.initial_size=1G
        - NEO4J_dbms_memory_heap_max__size=1G
