CREATE (FirstEMove:EMove {d:50, v:'0.4'})
CREATE (FirstMove)-[:DIMENSION]->(FirstEMove)
CREATE (SecondMove:Move {m:'d1', n:0, c:'B', t:'wx'})
CREATE (SecondEMove:EMove {d:30, v:'0.7'})
CREATE (SecondMove)-[:DIMENSION]->(SecondEMove)
CREATE (ThirdMove:Move {m:'d2', n:1, c:'C', t:'wz'})
CREATE (ThirdEMove:EMove {d:31, v:'0.6'})
CREATE (ThirdMove)-[:DIMENSION]->(ThirdEMove)
CREATE (FirstMove)-[:MOVE]->(SecondMove)
CREATE (FirstMove)-[:MOVE]->(ThirdMove)