server:
  port: 8080
spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      database: chegura
    authentication:
      username: neo4j
      password: secret

logging:
  level:
    org:
      springframework:
        data:
          neo4j:
            cypher: trace
